stages:
  - build
  - test

# Cache
cache: &girara_cache
  key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
  paths:
    - subprojects/girara

# Archlinux
build:archlinux:
  tags:
    - pwmt
  stage: build
  image: registry.pwmt.org/pwmt/gitlab-runner-images/archlinux:latest
  script:
    - meson subprojects update
    - mkdir -p build && cd build
    - meson --force-fallback-for=girara ..
    - ninja
  cache:
    <<: *girara_cache
  artifacts:
    expire_in: 6 hours
    paths:
      - build
  except:
    - tags

test:archlinux:
  tags:
    - pwmt
  stage: test
  image: registry.pwmt.org/pwmt/gitlab-runner-images/archlinux:latest
  script:
    - cd build
    - ninja test
  cache:
    <<: *girara_cache
    policy: pull
  dependencies:
    - build:archlinux
  except:
    - tags

# Debian 12 (bookworm)
build:debian-bookworm:
  tags:
    - pwmt
  stage: build
  image: registry.pwmt.org/pwmt/gitlab-runner-images/debian:bookworm
  script:
    - meson subprojects update
    - mkdir -p build && cd build
    - meson --force-fallback-for=girara ..
    - ninja
  cache:
    <<: *girara_cache
  artifacts:
    expire_in: 6 hours
    paths:
      - build
  except:
    - tags

test:debian-bookworm:
  tags:
    - pwmt
  stage: test
  image: registry.pwmt.org/pwmt/gitlab-runner-images/debian:bookworm
  script:
    - cd build
    - ninja test
  cache:
    <<: *girara_cache
    policy: pull
  dependencies:
    - build:debian-bookworm
  except:
    - tags

# Debian 13 (trixie)
build:debian-trixie:
  tags:
    - pwmt
  stage: build
  image: registry.pwmt.org/pwmt/gitlab-runner-images/debian:trixie
  script:
    - meson subprojects update
    - mkdir -p build && cd build
    - meson --force-fallback-for=girara ..
    - ninja
  cache:
    <<: *girara_cache
  artifacts:
    expire_in: 6 hours
    paths:
      - build
  except:
    - tags

test:debian-trixie:
  tags:
    - pwmt
  stage: test
  image: registry.pwmt.org/pwmt/gitlab-runner-images/debian:trixie
  script:
    - cd build
    - ninja test
  cache:
    <<: *girara_cache
    policy: pull
  dependencies:
    - build:debian-trixie
  except:
    - tags

# Ubuntu 22.04 LTS (jammy)
build:ubuntu-jammy:
  tags:
    - pwmt
  stage: build
  image: registry.pwmt.org/pwmt/gitlab-runner-images/ubuntu:jammy
  script:
    - meson subprojects update
    - mkdir -p build && cd build
    - meson --force-fallback-for=girara ..
    - ninja
  cache:
    <<: *girara_cache
  artifacts:
    expire_in: 6 hours
    paths:
      - build
  except:
    - tags

test:ubuntu-jammy:
  tags:
    - pwmt
  stage: test
  image: registry.pwmt.org/pwmt/gitlab-runner-images/ubuntu:jammy
  script:
    - cd build
    - ninja test
  cache:
    <<: *girara_cache
    policy: pull
  dependencies:
    - build:ubuntu-jammy
  except:
    - tags

# Ubuntu 24.04 LTS (noble)
# build:ubuntu-noble:
#   tags:
#     - pwmt
#   stage: build
#   image: registry.pwmt.org/pwmt/gitlab-runner-images/ubuntu:noble
#   script:
#     - meson subprojects update
#     - mkdir -p build && cd build
#     - meson --force-fallback-for=girara ..
#     - ninja
#   cache:
#     <<: *girara_cache
#   artifacts:
#     expire_in: 6 hours
#     paths:
#       - build
#   except:
#     - tags

# test:ubuntu-noble:
#   tags:
#     - pwmt
#   stage: test
#   image: registry.pwmt.org/pwmt/gitlab-runner-images/ubuntu:noble
#   script:
#     - cd build
#     - ninja test
#   cache:
#     <<: *girara_cache
#     policy: pull
#   dependencies:
#     - build:ubuntu-noble
#   except:
#     - tags
